### ISSUE TITLE
doc: fix the doc rendering

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylla-cloud-getting-started#11]
Some pages look good, for example, Quick Start: Python. Others look weird and show up erratically on the menu:

![image](https://github.com/scylladb/scylla-cloud-getting-started/assets/37244380/73578766-b783-4865-a977-03c0f02f0e82)

![image](https://github.com/scylladb/scylla-cloud-getting-started/assets/37244380/a9630b08-c83a-48ce-b03b-8d8411b79bb7)

Run `make preview `to preview the docs and verify if the pages look OK.

**Comment by dgarcia360** [comment]
Taking this issue
