### ISSUE TITLE
Remove the personalized twitter handle

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-cloud-getting-started#15]
We should not use a private handle in the docs.
Instead, we can add a generic Twitte this page handle to the Theme.
@annastuchlik 

> Did you like the content? [Tweet about it](https://twitter.com/intent/tweet?url=https%3A%2F%2Fgithub.com%2Fscylladb%2Fscylla-cloud-getting-started&via=scylladb%20%40danielhe4rtless&text=Just%20finished%20the%20ScyllaDB%20Hello%20World%20in%20Rust&hashtags=scylladb%20%23nodejs)!

![image](https://github.com/scylladb/scylla-cloud-getting-started/assets/170200/acfb2cf3-4501-4bec-9183-cf50bbd4e3eb)

**Comment by annastuchlik** [comment]
I'm not sure how useful that would be, as tweeting about documentation pages is not popular whatsoever. I've created an issue just to remember to discuss it. 

@DanielHe4rt The current "Tweet about it" should still be removed from the docs.

**Comment by DanielHe4rt** [comment]
IMHO its a way to remeber that we're present in Twitter as well. But I understand that isn't so popular at all.

Fixing this ASAP and closing the issue after that.

**Comment by DanielHe4rt** [comment]
Closed!
