### ISSUE TITLE
Add a documention theme

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-cloud-getting-started#3]
see https://sphinx-theme.scylladb.com/ for instructions

**Comment by tzach** [comment]
@annastuchlik please advice

**Comment by annastuchlik** [comment]
@DanielHe4rt 
The documentation should be published to http://cloud-getting-started.scylladb.com/.  It has been added to our DNS, so you can proceed with the updates to this repository.

**You should install the documentation theme following the installation guide** at https://sphinx-theme.scylladb.com/stable/getting-started/installation.html.
The same guide was followed to create the recent Feature Store Example documentation, so you can see the project structure and configuration as an example: https://github.com/scylladb/scylladb-feature-store/tree/master/docs

Should you need assistance, please contact David Garcia @dgarcia360 to schedule a meeting where you can set up the configuration together.

Let me know if you have any questions

**Comment by DanielHe4rt** [comment]
Hey @annastuchlik! I did the full setup described at the documentation but at the DNS page it shows up trying validate the domain. 

![image](https://github.com/scylladb/scylla-cloud-getting-started/assets/6912596/d9823acd-6cdc-42ee-9f8b-cd8d42729678)

Also I'm getting an error on `make multiversion` command. cc: @dgarcia360 

![image](https://github.com/scylladb/scylla-cloud-getting-started/assets/6912596/41799d67-0e06-4389-9ade-e4fc3c91102c)

**Comment by annastuchlik** [comment]
Hi Daniel,

Please use `make preview` to run a local preview. I was able to run a local preview (and I'm going to open a few issues as a follow-up).

When did you try to publish the docs? It may take 24h for the changes to propagate. If it still doesn't work, please contact @dgarcia360  (you can find him on the User Slack).

**Comment by DanielHe4rt** [comment]
I published has a few days already. I think that has something with the DNS and I mailed Boris about that.

**Comment by annastuchlik** [comment]
It looks like https://cloud-getting-started.scylladb.com/stable/ is up and the Sphinx theme is applied.
However, the problems reported in https://github.com/scylladb/scylla-cloud-getting-started/issues/11 make some sections impossible to use.

**Comment by DanielHe4rt** [comment]
Closing the issue since it's already deployed.
