### ISSUE TITLE
doc: remove the branch selector from the docs

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylla-cloud-getting-started#35]
The selector only shows the main branch, which looks bad. 
![image](https://github.com/scylladb/scylla-cloud-getting-started/assets/37244380/d2dad3b6-198b-4a6a-8562-06356682a035)

Update the configuration to remove the selector.
Ask @dgarcia360 for help if needed.

**Comment by DanielHe4rt** [comment]
I'll take a look on how to remove it. There's any other docsite with this feature already implemented?
