### ISSUE TITLE
Add the site to the doc search engine

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-cloud-getting-started#4]

**Comment by DanielHe4rt** [comment]
@annastuchlik now I think that the landing page is fine to be indexed. Could you help me on that?

**Comment by DanielHe4rt** [comment]
Hey! I removed the duplicated hero from the main page and added more context into the Alternator page. 

Seems that now it's suppose to be two different things. Let me know if anything strange appears!

**Comment by DanielHe4rt** [comment]
Cool! I'm closing this issue then. 

Thanks Anna.
